# Generated by Django 2.2.1 on 2019-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t',
            fields=[
                ('tid', models.TextField(default='QQQ', max_length=3, primary_key=True, serialize=False)),
            ],
        ),
    ]
